### ISSUE TITLE
How to use slog and prefix operator in tantivy-py

### ISSUE THREAD

**Issue by JRatschat** [quickwit-oss/tantivy-py#127] opened 2023-09-13 09:58 UTC
Hi all,

Thanks first of all for the amazing repo!

I have been searching for additional valid query formats in the documentation (https://docs.rs/tantivy/latest/tantivy/query/struct.QueryParser.html) and I was wondering how I can use the slop operator (e.g., "big wolf"~1 will return documents containing the phrase "big bad wolf") and the prefix operator (e.g., "big bad wo"* will match "big bad wolf") in the tantivy-py implementation.

Are these operators already implemented? If yes, could you provide an example for both cases?

Thanks so much!

**Comment by cjrh** [comment] 2023-09-13 10:28
I played around with a unit test:

```python
    def test_slop_search(self, dir_index):
        _, index = dir_index
        query = index.parse_query('title:"the man"~2')

        result = index.searcher().search(query, 10)
        _, doc_address = result.hits[0]
        searched_doc = index.searcher().doc(doc_address)
        assert searched_doc["title"] == ['The Old Man and the Sea']
        assert len(result.hits) == 1
```

Prefix should also work since we just pass the query string through directly. Does this help?

**Comment by JRatschat** [comment] 2023-09-13 10:56
Thanks for your quick reply!

I also played around with my own data and your solution for the slop operator works :)

Let's change the title a bit to get my following point across:

Instead of title=["The Old Man and the Sea"], let's use title=["The Old Manhood and the Sea"].

Concerning the prefix operator, this code works:

```
def test_slop_search(self, dir_index):
        _, index = dir_index
        query = index.parse_query('title:"old man"*')

        result = index.searcher().search(query, 10)
        _, doc_address = result.hits[0]
        searched_doc = index.searcher().doc(doc_address)
        assert searched_doc["title"] == ['The Old Manhood and the Sea']
        assert len(result.hits) == 1
```

While I get the following error when changing "old man"* to "man"*:
`ValueError: The phrase '"man"' does not produce at least two terms using the tokenizer '"default"'
`

If I only use `query = index.parse_query('title:man*)`, nothing is fetched although `assert searched_doc["title"] == ['The Old Manhood and the Sea']` should in my understanding still be true. The same problem appears if I want to use the fuzzy search functionality `query = index.parse_query('title:manhoo~1)`.

Any idea why this is the case?

**Comment by cjrh** [comment] 2023-09-13 11:36
In short, I am not sure.

If you want to get an authoritative answer, this would have to be a question for the upstream tantivy project methinks. We just pass the query string directly through to the underlying tantivy library.  My suggestion, if this is workable for you, is to reproduce the bahaviour using the upstream (Rust) tantivy library and then ask with that reproducer on their tracker.

**Comment by adamreichold** [comment] 2023-09-14 07:52
> While I get the following error when changing "old man"* to "man"*:
ValueError: The phrase '"man"' does not produce at least two terms using the tokenizer '"default"' 

This is the expected behaviour, the `*` syntax corresponds to the [`PhrasePrefixQuery`](https://docs.rs/tantivy/latest/tantivy/query/struct.PhrasePrefixQuery.html) which needs at least two tokens, the first one for the phrase query and the second one which will be expanded as a prefix.

**Comment by JRatschat** [comment] 2023-09-14 09:18
Understood, thanks for clarifying!

**Comment by cjrh** [comment] 2023-09-14 09:59
@JRatschat are you ok to close this issue?

**Comment by cjrh** [comment] 2023-09-27 21:49
Closing because I think the question was answered, but if not I am happy to reopen.

**Closed by cjrh** 2023-09-27 21:49 UTC
Labels: documentation, question
